## mybatis configuration
ibatis:
  config:
    aliases: fs.service.business.demoservice.*.entity
  ##mapper locations
  mapper:
    locations:
      fsAppByCatering: classpath:mapper/test/*.xml
server:
  port: 8765
## application name
spring:
  ##解决jvm使用的冲突，tomcat中不同的server 注册jmx必须使用不同的jvm
  jmx:
    default-domain: service-demo
  ## 当前服务名称
  application:
    name: service-demo
  ## jwt configuration
  security:
    jwt:
      cert:
        pub: public.cert
  profiles:
    active: hejian
## 资源服务器url 后缀模板配置
resource:
  server:
    configuration:
      permitted: /v2/api-docs
      authenticated: /**