ibatis:
  config:
    aliases: com.service.*.entity
  ##mapper locations
  mapper:
    locations:
      test: classpath:mapper/test/*.xml
      ## 配置dao扫描路径
    packages:
      path: com.service.*.dao
##eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
## application name
spring:
  application:
    name: service-demo
  security:
    jwt:
      cert:
        pub: public.cert

    ## datasource configuration
datasource:
  fsappbycatering:
    name: fsAppByCatering
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: jdbc:sqlserver://47.111.168.225:8899;DatabaseName=fsAppByCatering
    username: fstest
    password: Fsgf@2017

security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:9098/oauth/token_key
    client:
      client-id: android
      client-secret: android
      access-token-uri: http://localhost:9098/oauth/token
      grant-type: password
      scope: xx
      user-authorization-uri: http://localhost:9098/oauth/authorize
## swagger config
swagger:
  config:
    enable: true
    path: com.service.demo.controller
  api:
    title: demo Api文档


